server:
  port: 8090
eureka:
  client:
    service-url:
      defaultZone: http://serverOne:8080/eureka/
  instance:
    instance-id: miaosha
spring:
  application:
    name: server-miaosha
  redis:
    host: 127.0.0.1
    port: 6379

mybatis-plus:
  mapper-locations: classpath:mappers/*.xml